#!/bin/sh
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)

    if [ "master" = "$branch" ]; then
        mkdir /home/git/wtfwords
        cd /home/git/wtfwords

        echo "Check out local copy"
        git --work-tree=/home/git/wtfwords --git-dir=/home/git/wtfwords.git checkout -f

        chmod 770 ./gradlew
        ./gradlew build -x test

        mkdir /home/git/wtfwords/logs
        service wtfwords restart

        echo Complete.
    fi

    if [ "release" = "$branch" ]; then
        git push prod release -f
        echo Complete.
    fi
done


