#!/bin/sh
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)

    if [ "master" = "$branch" ]; then
        pkill -f wtfwords-1.0-SNAPSHOT

        mkdir /home/git/wtfwords
        cd /home/git/wtfwords

        echo "Check out local copy"
        git --work-tree=/home/git/wtfwords --git-dir=/home/git/wtfwords.git checkout -f

        chmod 770 ./gradlew
        ./gradlew build -x test

        mkdir /home/git/wtfwords/logs
        nohup java -jar build/libs/wtfwords-1.0-SNAPSHOT.jar > /home/git/wtfwords/logs/main.log 2>&1 &

        echo Complete.
    fi

    if [ "release" = "$branch" ]; then
		export GOROOT=/usr/lib/go
		export GOPATH=/home/git/gopath
		export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
		export DATABASE_URL=127.0.0.1:33333

		rm -rf /home/git/gopath/src/gochat
		mkdir /home/git/gopath/src/gochat

		cd /home/git/gopath/src/gochat

		git --work-tree=/home/git/gopath/src/gochat --git-dir=/home/git/gochat.git checkout -f release

		go install gochat/main

		#docker start mongodb
		#go test ./...
		#docker stop mongodb

		unset GIT_DIR
		godep save ./...

		git config --global user.email "artem.chuzhmarov@gmail.com"
		git config --global user.name "Artem Chuzhmarov"

		git init
		git add .
		git commit -m "add dependencies"
		git remote add ocean dokku@wtfchat.wtf:gochat

		git push ocean master -f
	fi
done

